###1.Explain different types of views. Demonstrate with suitable examples.

**Ans**. In SQL, a view is a virtual table that is based on the result of a SELECT query. Views do not store the data themselves but provide a way to represent the data stored in one or more tables in a predefined manner. Views can simplify complex queries, provide security by restricting access to specific columns or rows, and offer a way to present data in a more organized and understandable form.

  1.Simple View:

      A simple view is based on a single table and can include all or some of its columns.
      It is created using a basic SELECT statement.

CREATE VIEW EmployeeView AS

SELECT EmployeeID, FirstName, LastName, Salary

FROM Employees;

  2.Complex View:

      A complex view is based on multiple tables. It can involve joins, calculations, and other operations.
      It is useful for presenting data in a consolidated form.

-- Creating a complex view

CREATE VIEW SalesSummary AS

SELECT ProductID, SUM(Quantity) AS TotalQuantity, AVG(Price) AS AvgPrice

FROM OrderDetails

GROUP BY ProductID;

  3.Indexed View:

      Also known as a materialized view, an indexed view is a view that has been indexed to improve query performance.
      It stores the result set in a physical form, allowing for faster retrieval.

      -- Creating an indexed view

CREATE VIEW SalesSummaryIndexed

WITH SCHEMABINDING

AS

SELECT ProductID, SUM(Quantity) AS TotalQuantity, AVG(Price) AS AvgPrice

FROM dbo.OrderDetails

GROUP BY ProductID;

-- Creating an index on the indexed view

CREATE UNIQUE CLUSTERED INDEX IX_SalesSummary_ProductID

ON SalesSummaryIndexed (ProductID);

  4.Updatable View:

      An updatable view allows modifications to the underlying tables through the view.
      Certain conditions must be met for a view to be updatable, such as having a unique key in the underlying table.

-- Creating an updatable view

CREATE VIEW UpdatableView AS

SELECT CustomerID, ContactName, City

FROM Customers

WHERE Country = 'USA';

  5.Partitioned View:

      A partitioned view is used to manage large amounts of data by dividing it into smaller, more manageable pieces.
      Each partition of the view can be stored on a different server or database.
-- Creating a partitioned view

CREATE VIEW SalesPartitionedView AS

SELECT * FROM SalesData2019

UNION ALL

SELECT * FROM SalesData2020;

###2.What is the difference between function and stored procedure? Write syntax for creating functions and stored procedures
**Ans.**
In SQL, functions and stored procedures are both database objects that contain a set of SQL statements. However, they serve different purposes and have some key differences:

  Stored Procedure:

      A stored procedure is a precompiled collection of one or more SQL statements that can be executed as a single unit.
      It can have input and output parameters, making it versatile for performing various tasks.
      Stored procedures can return multiple result sets.
      They are typically used for tasks such as data manipulation, data validation, and business logic implementation.
      They are invoked using the EXECUTE or EXEC statement.

  Function:

      A function is a reusable piece of code that performs a specific task and returns a single value.
      Functions take parameters as input and return a single value, which can be used in SQL expressions.
      Functions cannot have output parameters or return multiple result sets.
      They are commonly used in expressions, such as in the SELECT statement or WHERE clause.
      Functions can be used in computed columns, making them useful for calculations.

**Stored Procedure Syntax:**

-- Creating a stored procedure with input parameter

CREATE PROCEDURE GetEmployeeName

   @EmployeeID INT

AS

BEGIN

  SELECT FirstName + ' ' + LastName AS FullName

  FROM Employees
  
   WHERE EmployeeID = @EmployeeID;

END;

**Function Syntax:**

-- Creating a scalar function with input parameters

CREATE FUNCTION CalculateTotalSalary

   (@DepartmentID INT)

RETURNS DECIMAL(10, 2)

AS

BEGIN

   DECLARE @TotalSalary DECIMAL(10, 2);

   SELECT @TotalSalary = SUM(Salary)

   FROM Employees

   WHERE DepartmentID = @DepartmentID;

   RETURN @TotalSalary;

END;

It's important to note that the specific syntax and features may vary depending on the database system you are using (e.g., SQL Server, MySQL, PostgreSQL). The examples provided use Transact-SQL syntax for SQL Server, and you may need to adjust the syntax based on the database system you are working with.

###3.What is an index in SQL? What are the different types of indexes in SQL?

**Ans.**
In SQL, an index is a database object that provides a quick and efficient method for looking up rows in a table based on the values in one or more columns. Indexes play a crucial role in optimizing query performance by allowing the database engine to locate and retrieve data more rapidly. Instead of scanning the entire table, the database can use the index to directly access the rows that satisfy the conditions specified in a query.

Here are some common types of indexes in SQL:
  
  1.Clustered Index:

      A clustered index determines the physical order of the data in the table.
      There can be only one clustered index per table because the data rows themselves are stored in the order defined by the clustered index.
      When a table has a clustered index, the rows are stored on disk in the same order as the index.

  2.Non-Clustered Index:

      A non-clustered index does not affect the physical order of the data on disk.
      The index contains a separate structure that includes a mapping of index key values to the corresponding row locations.
      A table can have multiple non-clustered indexes.

  3.Unique Index:

      A unique index ensures that the values in the indexed columns are unique across all rows in the table.
      It is similar to a non-clustered index but enforces uniqueness.

These are just a few examples of index types in SQL. The choice of which index to use depends on the specific requirements and characteristics of the data, as well as the types of queries that need to be optimized. Keep in mind that while indexes can significantly improve query performance, they also introduce overhead during data modification operations (inserts, updates, and deletes), so they should be chosen and maintained carefully based on the workload and usage patterns.

###4.Showcase an example of exception handling in SQL stored procedure.
**Ans.** In SQL Server, you can use the TRY...CATCH block for exception handling within stored procedures. Here's an example of a stored procedure with exception handling:

 -- Creating a sample table

CREATE TABLE Employee (

  EmployeeID INT PRIMARY KEY,
  
  FirstName NVARCHAR(50),
  
  LastName NVARCHAR(50),
  
  Salary DECIMAL(10, 2)

);

-- Creating a stored procedure with exception handling

CREATE PROCEDURE InsertEmployee

   @EmployeeID INT,

   @FirstName NVARCHAR(50),

   @LastName NVARCHAR(50),

   @Salary DECIMAL(10, 2)

AS

BEGIN

   BEGIN TRY

     -- Attempt to insert the data into the Employee table

      INSERT INTO Employee (EmployeeID, FirstName, LastName, Salary)
      VALUES (@EmployeeID, @FirstName, @LastName, @Salary);

     -- If the insertion is successful, print a success message
        
     PRINT 'Employee inserted successfully.';
   
   END TRY
  
   BEGIN CATCH
  
     -- If an error occurs, handle the exception
  
   PRINT 'Error occurred: ' + ERROR_MESSAGE();
  
  END CATCH

END;

###5.Create a SQL function to split strings into rows on a given character? Input String: Stephen;peter;berry;Olivier;caroline;

**Ans** Here's an example using SQL Server. Note that the exact syntax may vary depending on the database system you're using:

CREATE FUNCTION dbo.SplitStringIntoRows

(

   @InputString NVARCHAR(MAX),

   @Delimiter CHAR(1)

)

RETURNS TABLE

AS

RETURN

(

   SELECT value AS SplitValue

   FROM STRING_SPLIT(@InputString, @Delimiter)

);

This function uses the STRING_SPLIT function available in SQL Server, which splits a string into rows based on a specified delimiter. The function takes two parameters: @InputString is the input string to be split, and @Delimiter is the character on which to split the string.

SplitValue
----------
Stephen

peter

berry

Olivier

caroline

Please note that the availability of the STRING_SPLIT function depends on your SQL Server version. If you are using a different database system, the approach may differ. In such cases, you might need to use a custom split function or another built-in function specific to your database system.

###6.What is a temporary and a variable table? Write suitable syntax to create temporary tables and variable tables.
**Ans** Temporary tables and table variables are both used to store and manipulate data within the scope of a session or a batch of queries in SQL Server. However, they have some differences in terms of their lifespan, scope, and behavior.

Temporary Table:

      A temporary table is a physical table that is created and stored in the tempdb system database.
      It exists for the duration of a session or a specific batch of queries.
      Multiple sessions can have their own versions of the same temporary table, and they do not interfere with each other.
      Temporary tables are explicitly created and dropped by the user.

Syntax for Creating a Temporary Table:

-- Creating a temporary table

CREATE TABLE #TempTable

(

   ID INT,
   Name NVARCHAR(50)

);

-- Inserting data into the temporary table

INSERT INTO #TempTable (ID, Name)
VALUES (1, 'John'), (2, 'Jane');

-- Querying the temporary table

SELECT * FROM #TempTable;

-- Dropping the temporary table (should be explicitly dropped when done)

DROP TABLE #TempTable;

**Table Variable:**

      A table variable is a variable of table type that exists only for the duration of the batch, stored procedure, or function in which it is declared.
      It is created and used similarly to other variables, but it represents a table structure.
      Table variables are automatically deallocated when the batch or procedure completes.

-- Creating a table variable

DECLARE @TableVariable TABLE

(

   ID INT,
   Name NVARCHAR(50)

);

-- Inserting data into the table variable

INSERT INTO @TableVariable (ID, Name)
VALUES (1, 'John'), (2, 'Jane');

-- Querying the table variable

SELECT * FROM @TableVariable;

Choose between temporary tables and table variables based on my specific requirements, such as the need for indexing, the size of the data, and the scope of the data within your application or query.